name = "sentinel-app"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
API_URL = "https://sentinel.taxinearme.sk"
NEXT_PUBLIC_API_URL = "https://sentinel.taxinearme.sk/api"
