[build]
builder = "nixpacks"
buildCommand = "cd apps/api && npx prisma generate --schema=../../packages/shared/prisma/schema.prisma && npm run build"

[deploy]
startCommand = "cd apps/api && node dist/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
